module eth_tse_0_intel_lvds_core10_191_vvutosq #(
   parameter NUM_CHANNELS                                       = 0,
   parameter J_FACTOR                                           = 0,
   parameter RX_BITSLIP_ROLLOVER                                = 0,
   parameter TX_REGISTER_CLOCK                                  = "",
   parameter TX_OUTCLOCK_NON_STD_PHASE_SHIFT                    = "",
   parameter TX_CHANNELS                                        = 0,
   parameter RX_CHANNELS                                        = 0,
   parameter SERDES_DPA_MODE                                    = "",
   parameter SERDES_FACTOR                                      = "",
   parameter BITSLIP_MAX                                        = "",
   parameter BITSLIP_FUNC                                       = "",
   parameter VCO_DIV_EXPONENT                                   = 0,
   parameter SER_CLK_FUNCTION                                   = "",
   parameter FILTER_CODE                                        = "",
   parameter FILTER_CODE_CPA                                    = "",
   parameter SILICON_REV                                        = "",
   parameter DPA_DIV_VAL                                        = "",
   parameter CORE0_DIV_VAL                                      = "",
   parameter CORE1_DIV_VAL                                      = "",
   parameter UFI_MODE                                           = "",
   parameter UFI_CLK_SEL                                        = "",
   parameter UFI_LOCK_COUNTER                                   = 0,
   parameter SYNTH_FOR_SIM                                      = 0,
   parameter VCO_FREQUENCY                                      = 0,
   parameter TX_OUTCLOCK_ENABLED                                = "",
   parameter TX_OUTCLOCK_DIV_WORD                               = 0,
   parameter EXTERNAL_PLL                                       = "",
   parameter USE_BITSLIP                                        = "",
   parameter USE_CPA                                            = "",
   parameter USE_CPA_RECONFIG                                   = "",
   parameter NUM_CLOCKS                                         = 0,
   parameter WIDE_CT                                            = "",
   parameter DPRIO_ENABLED                                      = "",
   parameter USE_DUPLEX                                         = ""
) (
   input  logic [9:0]      tx_in,
   output logic [0:0]      tx_out_p,
   output logic [0:0]      tx_out_n,
   output logic            tx_outclock_p,
   output logic            tx_outclock_n,
   output logic            tx_coreclock,
   input  logic [0:0]      rx_in_p,
   input  logic [0:0]      rx_in_n,
   output logic [9:0]      rx_out,
   input  logic [0:0]      rx_bitslip_reset,
   input  logic [0:0]      rx_bitslip_ctrl,
   output logic [0:0]      rx_bitslip_max,
   input  logic            pll_areset,
   output logic [0:0]      rx_dpa_locked,
   input  logic [0:0]      rx_dpa_hold,
   input  logic [0:0]      rx_dpa_reset,
   input  logic [0:0]      rx_fifo_reset,
   output logic [0:0]      rx_divfwdclk,
   input  logic [0:0]      loopback_in,
   output logic [0:0]      loopback_out,
   input  logic            user_dprio_rst_n,
   input  logic            user_dprio_read,
   input  logic [8:0]      user_dprio_reg_addr,
   input  logic            user_dprio_write,
   input  logic [7:0]      user_dprio_writedata,
   input  logic            user_dprio_clk_in,
   input  logic            user_mdio_dis,
   output logic            user_dprio_clk,
   output logic            user_dprio_block_select,
   output logic [7:0]      user_dprio_readdata,
   output logic            user_dprio_ready,
   input  logic [7:0]      ext_vcoph,
   input  logic [1:0]      ext_lvds_clk,
   input  logic [1:0]      ext_loaden,
   input  logic            ext_coreclock,
   input  logic            ext_pll_locked,
   output logic            rx_coreclock,
   output logic            pll_locked
);
   timeunit 1ns;
   timeprecision 1ps;

   intel_lvds_core10_eth_tse_0_intel_lvds_core10_191_vvutosq # (
      .NUM_CHANNELS (NUM_CHANNELS),
      .J_FACTOR (J_FACTOR),
      .RX_BITSLIP_ROLLOVER (RX_BITSLIP_ROLLOVER),
      .TX_REGISTER_CLOCK (TX_REGISTER_CLOCK),
      .TX_OUTCLOCK_NON_STD_PHASE_SHIFT (TX_OUTCLOCK_NON_STD_PHASE_SHIFT),
      .TX_CHANNELS (TX_CHANNELS),
      .RX_CHANNELS (RX_CHANNELS),
      .SERDES_DPA_MODE (SERDES_DPA_MODE),
      .SERDES_FACTOR (SERDES_FACTOR),
      .BITSLIP_MAX (BITSLIP_MAX),
      .BITSLIP_FUNC (BITSLIP_FUNC),
      .VCO_DIV_EXPONENT (VCO_DIV_EXPONENT),
      .SER_CLK_FUNCTION (SER_CLK_FUNCTION),
      .FILTER_CODE (FILTER_CODE),
      .FILTER_CODE_CPA (FILTER_CODE_CPA),
      .SILICON_REV (SILICON_REV),
      .DPA_DIV_VAL (DPA_DIV_VAL),
      .CORE0_DIV_VAL (CORE0_DIV_VAL),
      .CORE1_DIV_VAL (CORE1_DIV_VAL),
      .UFI_MODE (UFI_MODE),
      .UFI_CLK_SEL (UFI_CLK_SEL),
      .UFI_LOCK_COUNTER (UFI_LOCK_COUNTER),
      .SYNTH_FOR_SIM (SYNTH_FOR_SIM),
      .VCO_FREQUENCY (VCO_FREQUENCY),
      .TX_OUTCLOCK_ENABLED (TX_OUTCLOCK_ENABLED),
      .TX_OUTCLOCK_DIV_WORD (TX_OUTCLOCK_DIV_WORD),
      .EXTERNAL_PLL (EXTERNAL_PLL),
      .USE_BITSLIP (USE_BITSLIP),
      .USE_CPA (USE_CPA),
      .USE_CPA_RECONFIG (USE_CPA_RECONFIG),
      .NUM_CLOCKS (NUM_CLOCKS),
      .WIDE_CT (WIDE_CT),
      .DPRIO_ENABLED (DPRIO_ENABLED),
      .USE_DUPLEX (USE_DUPLEX)
   ) arch_inst (
      .tx_in (tx_in),
      .tx_out_p (tx_out_p),
      .tx_out_n (tx_out_n),
      .tx_outclock_p (tx_outclock_p),
      .tx_outclock_n (tx_outclock_n),
      .tx_coreclock (tx_coreclock),
      .rx_in_p (rx_in_p),
      .rx_in_n (rx_in_n),
      .rx_out (rx_out),
      .rx_bitslip_reset (rx_bitslip_reset),
      .rx_bitslip_ctrl (rx_bitslip_ctrl),
      .rx_bitslip_max (rx_bitslip_max),
      .pll_areset (pll_areset),
      .rx_dpa_locked (rx_dpa_locked),
      .rx_dpa_hold (rx_dpa_hold),
      .rx_dpa_reset (rx_dpa_reset),
      .rx_fifo_reset (rx_fifo_reset),
      .rx_divfwdclk (rx_divfwdclk),
      .loopback_in (loopback_in),
      .loopback_out (loopback_out),
      .user_dprio_rst_n (user_dprio_rst_n),
      .user_dprio_read (user_dprio_read),
      .user_dprio_reg_addr (user_dprio_reg_addr),
      .user_dprio_write (user_dprio_write),
      .user_dprio_writedata (user_dprio_writedata),
      .user_dprio_clk_in (user_dprio_clk_in),
      .user_mdio_dis (user_mdio_dis),
      .user_dprio_clk (user_dprio_clk),
      .user_dprio_block_select (user_dprio_block_select),
      .user_dprio_readdata (user_dprio_readdata),
      .user_dprio_ready (user_dprio_ready),
      .ext_vcoph (ext_vcoph),
      .ext_lvds_clk (ext_lvds_clk),
      .ext_loaden (ext_loaden),
      .ext_coreclock (ext_coreclock),
      .ext_pll_locked (ext_pll_locked),
      .rx_coreclock (rx_coreclock),
      .pll_locked (pll_locked)
   );
endmodule
